// File: computer_networks_ch1.js

const computerNetCh1Data = [
    // --- Topic: Introduction & Signals ---
    {
        "question": "In a Data Communication System, what is the term for the information (e.g., 'Hello World') being transmitted?",
        "options": ["Protocol", "Medium", "Data", "Signal"],
        "correct": 2,
        "explanation": "Data refers to the context or information that needs to be transmitted from the sender to the receiver."
    },
    {
        "question": "Which component is defined as a 'set of rules that governs transmission of data'?",
        "options": ["Sender", "Protocol", "Medium", "Receiver"],
        "correct": 1,
        "explanation": "A Protocol is the set of rules determining how data is transmitted."
    },
    {
        "question": "For data to be transmitted through a medium, it must be transformed into:",
        "options": ["Binary code", "Electromagnetic signals", "Hexadecimal format", "ASCII text"],
        "correct": 1,
        "explanation": "Data must be transformed into electromagnetic signals to pass through a transmission medium."
    },
    {
        "question": "Which type of signal is represented by continuous waveforms?",
        "options": ["Digital signal", "Analog signal", "Discrete signal", "Baseband signal"],
        "correct": 1,
        "explanation": "Analog signals are continuous waveforms, whereas digital signals are discrete."
    },
    {
        "question": "Which type of signal uses discrete forms (0s and 1s)?",
        "options": ["Broadband signal", "Analog signal", "Digital signal", "Frequency signal"],
        "correct": 2,
        "explanation": "Digital signals represent data in discrete forms such as 0s and 1s (High or Low)."
    },
    {
        "question": "Signals always vary with respect to time or frequency. What is the relationship between time and frequency?",
        "options": ["Time = Frequency", "Time = 1 / Frequency", "Time = 2 * Frequency", "Time = Frequency^2"],
        "correct": 1,
        "explanation": "The text notes that Time = 1 / Frequency."
    },
    {
        "question": "A Baseband signal typically uses which type of signaling?",
        "options": ["Analog signals", "Digital signals", "Microwaves", "Radio waves"],
        "correct": 1,
        "explanation": "Baseband signal typically uses digital signals."
    },
    {
        "question": "A Broadband signal typically uses which type of signaling?",
        "options": ["Analog signals", "Digital signals", "Discrete pulses", "DC current"],
        "correct": 0,
        "explanation": "Broadband signal typically uses analog signals."
    },

    // --- Topic: Wired Transmission Media ---
    {
        "question": "Which transmission medium uses two wires twisted together in a helix fashion?",
        "options": ["Coaxial Cable", "Fiber Optic", "Twisted Pair", "Waveguide"],
        "correct": 2,
        "explanation": "Twisted Pair cables consist of two wires twisted together."
    },
    {
        "question": "Why are wires twisted in a Twisted Pair cable?",
        "options": ["To increase physical strength", "To disrupt the magnetic field and reduce interference", "To lower manufacturing costs", "To make the cable more flexible"],
        "correct": 1,
        "explanation": "Twisting the wires disrupts the magnetic field generated by the signal, which reduces interference."
    },
    {
        "question": "RJ-45 connectors are typically used with which type of cable?",
        "options": ["Coaxial Cable", "Fiber Optic", "Twisted Pair", "Waveguide"],
        "correct": 2,
        "explanation": "RJ-45 connectors are used with Twisted Pair cables (CAT 5) for Ethernet connections."
    },
    {
        "question": "What is the relationship between wire thickness and bandwidth in Twisted Pair cables?",
        "options": ["Thickness does not affect bandwidth", "Less thickness = more bandwidth", "More thickness = more bandwidth", "More thickness = less bandwidth"],
        "correct": 2,
        "explanation": "The text states: 'More the thickness of wire, more is the bandwidth'."
    },
    {
        "question": "Which cable has a copper core, insulating material, a braided outer conductor, and a plastic sheath?",
        "options": ["Twisted Pair", "Fiber Optic", "Coaxial Cable", "Radio Wave"],
        "correct": 2,
        "explanation": "This describes the structure of a Coaxial Cable."
    },
    {
        "question": "Which feature of Coaxial cable makes it superior to Twisted Pair?",
        "options": ["Lower cost", "Shielding and noise immunity", "Flexibility", "Ease of installation"],
        "correct": 1,
        "explanation": "Coaxial cable has better features than twisted pair because of its shielding, providing excellent noise immunity."
    },
    {
        "question": "Fiber Optics send information using:",
        "options": ["Electrons", "Light", "Sound waves", "Radio waves"],
        "correct": 1,
        "explanation": "Fiber optics sends information using light instead of electrons."
    },
    {
        "question": "In Fiber Optics, what is the layer immediately surrounding the core called?",
        "options": ["Jacket", "Sheath", "Cladding", "Insulator"],
        "correct": 2,
        "explanation": "Light travels through the core, which is surrounded by a layer called cladding."
    },
    {
        "question": "Which type of Fiber Optic cable allows light to travel in a single path?",
        "options": ["Multimode fiber", "Single-mode fiber", "Plastic fiber", "Dual-core fiber"],
        "correct": 1,
        "explanation": "Single-mode fiber allows light to travel in a Single Path."
    },
    {
        "question": "What is the typical range and speed of Single-mode fiber?",
        "options": ["2000 meters, Gb/s", "10 to 100 Km, Tb/s", "500 meters, Mb/s", "1 Km, Kb/s"],
        "correct": 1,
        "explanation": "Single-mode fiber can be used in 10 to 100 Km with data rates in Tb/s."
    },
    {
        "question": "Which type of fiber optic is characterized by light traveling in many paths and lower cost?",
        "options": ["Single-mode", "Multimode", "Tri-mode", "Uni-mode"],
        "correct": 1,
        "explanation": "Multimode fiber allows light to travel in many paths and has lower cost."
    },
    {
        "question": "If you need a fiber network for 1400 meters with a 1 Gb/s rate, which fiber should you choose?",
        "options": ["Single-mode", "Multimode", "Coaxial", "Twisted Pair"],
        "correct": 1,
        "explanation": "Multimode fiber is used for ranges up to 2000 meters and rates in Gb/s."
    },

    // --- Topic: Wireless & Spectrum ---
    {
        "question": "Which wireless waves are NOT frequently used for transmission because they do not propagate through buildings?",
        "options": ["Radio waves", "Microwaves", "Infrared", "UV, X, and Gamma rays"],
        "correct": 3,
        "explanation": "UV, X, and Gamma rays do not propagate through buildings and are hence not frequently used."
    },
    {
        "question": "Which portion of visible light can be used for information transmission?",
        "options": ["None", "Some portion", "All visible light", "Only Red light"],
        "correct": 1,
        "explanation": "The text states 'some portion of visible light' can be used as they can be modulated and amplified easily."
    },

    // --- Topic: Transmission Modes ---
    {
        "question": "In which transmission mode is the entire channel capacity dedicated to one-way transmission?",
        "options": ["Half-Duplex", "Full-Duplex", "Simplex", "Multi-Duplex"],
        "correct": 2,
        "explanation": "In Simplex mode (e.g., Radio), only one device sends data, using the entire channel."
    },
    {
        "question": "Walkie Talkies are an example of which transmission mode?",
        "options": ["Simplex", "Half-Duplex", "Full-Duplex", "Asynchronous"],
        "correct": 1,
        "explanation": "In Half-Duplex, devices can send and receive, but not simultaneously (e.g., Walkie Talkies)."
    },
    {
        "question": "Which transmission mode allows simultaneous two-way communication?",
        "options": ["Simplex", "Half-Duplex", "Full-Duplex", "Unicast"],
        "correct": 2,
        "explanation": "Full-Duplex mode allows both devices to send and receive data simultaneously (e.g., Telephone networks)."
    },

    // --- Topic: Topologies ---
    {
        "question": "In a Bus topology with 'n' devices, how many cables (links) are required?",
        "options": ["n", "n-1", "1", "n/2"],
        "correct": 2,
        "explanation": "Bus topology uses one shared backbone cable; therefore, only 1 main link is required."
    },
    {
        "question": "Which topology connects all devices to a central node (Hub or Switch)?",
        "options": ["Bus", "Ring", "Mesh", "Star"],
        "correct": 3,
        "explanation": "In a Star topology, each device has a point-to-point link to a central controller/hub."
    },
    {
        "question": "What is a major disadvantage of the Star topology?",
        "options": ["Difficult to install", "If the central node fails, the entire network goes down", "Fault detection is difficult", "Slow data transfer"],
        "correct": 1,
        "explanation": "The critical point of failure in a Star topology is the central node; if it fails, all connections fail."
    },
    {
        "question": "In a Ring topology, how is access to the network controlled to give every device a fair chance?",
        "options": ["By a central server", "Using a token", "Random access", "By priority bits"],
        "correct": 1,
        "explanation": "Ring topology uses a token passing mechanism to ensure fair access for transmission."
    },
    {
        "question": "What happens in a Ring topology if one node goes down?",
        "options": ["Only that node is affected", "The entire network goes down", "Data is rerouted automatically", "The server takes over"],
        "correct": 1,
        "explanation": "In a Ring topology, if any device fails, the entire network goes down."
    },
    {
        "question": "What is the formula for the number of physical links in a Mesh topology with 'n' devices?",
        "options": ["n", "n(n-1)", "n(n-1)/2", "n-1"],
        "correct": 2,
        "explanation": "In a fully connected Mesh topology, the number of links is calculated as n(n-1)/2."
    },
    {
        "question": "If a Mesh topology has 5 devices, how many physical links are required?",
        "options": ["5", "10", "20", "15"],
        "correct": 1,
        "explanation": "Using the formula n(n-1)/2: 5(4)/2 = 20/2 = 10 links."
    },
    {
        "question": "In a Mesh topology with 'n' devices, how many ports must be present on each device?",
        "options": ["n", "n-1", "1", "n/2"],
        "correct": 1,
        "explanation": "Each device connects to every other device, so it needs (n-1) ports."
    },
    {
        "question": "Which topology is known for high fault tolerance and privacy because of dedicated links?",
        "options": ["Bus", "Ring", "Star", "Mesh"],
        "correct": 3,
        "explanation": "Mesh topology has dedicated point-to-point links between all devices, ensuring privacy and robustness."
    },
    {
        "question": "Which topology is described as a collection of star topologies in a hierarchical level?",
        "options": ["Mesh", "Bus", "Tree", "Ring"],
        "correct": 2,
        "explanation": "Tree topology is a hierarchical structure consisting of multiple star topologies connected together."
    },
    {
        "question": "What is a disadvantage of Tree Topology?",
        "options": ["Difficult to expand", "If the central hub is down, the entire network goes down", "Cannot isolate networks", "Requires fewest cables"],
        "correct": 1,
        "explanation": "Like Star, if the central (primary) hub fails, the entire network goes down. It also requires more cabling than Bus."
    },

    // --- Topic: Network Types ---
    {
        "question": "Bluetooth works in which type of network category?",
        "options": ["LAN", "MAN", "WAN", "PAN"],
        "correct": 3,
        "explanation": "PAN (Personal Area Network) covers the range of a person, such as Bluetooth."
    },
    {
        "question": "A network covering a city (e.g., Cable TV) is classified as:",
        "options": ["LAN", "MAN", "WAN", "PAN"],
        "correct": 1,
        "explanation": "MAN (Metropolitan Area Network) spans across a city."
    },
    {
        "question": "Ethernet and WiFi are examples of:",
        "options": ["PAN", "LAN", "MAN", "WAN"],
        "correct": 1,
        "explanation": "Ethernet (wired) and WiFi (wireless) are technologies used in Local Area Networks (LAN)."
    },
    {
        "question": "The Internet is an example of which network type?",
        "options": ["LAN", "MAN", "WAN", "PAN"],
        "correct": 2,
        "explanation": "The Internet spans continents and the planet, making it a Wide Area Network (WAN)."
    },

    // --- Topic: OSI Model General ---
    {
        "question": "How many layers does the OSI model have?",
        "options": ["4", "5", "6", "7"],
        "correct": 3,
        "explanation": "The OSI (Open Systems Interconnection) model consists of 7 layers."
    },
    {
        "question": "What is the main aim of the OSI model?",
        "options": ["To create new hardware", "To allow communication between dissimilar systems", "To replace TCP/IP", "To increase internet speed"],
        "correct": 1,
        "explanation": "The aim is to allow two systems to communicate irrespective of their architecture without changing underlying logic."
    },
    {
        "question": "The process of a layer adding its own header to the packet received from the layer above is called:",
        "options": ["Decryption", "Encapsulation", "Routing", "Synchronization"],
        "correct": 1,
        "explanation": "Encapsulation is the process where a layer adds its header to the payload received from the upper layer."
    },
    {
        "question": "Which layers are considered 'Network Support Layers'?",
        "options": ["Session, Presentation, Application", "Physical, Data Link, Network", "Transport, Network, Data Link", "Application only"],
        "correct": 1,
        "explanation": "Physical, Data Link, and Network layers are the Network Support Layers."
    },
    {
        "question": "Which layers are considered 'User Support Layers'?",
        "options": ["Physical, Data Link, Network", "Session, Presentation, Application", "Transport only", "Network and Session"],
        "correct": 1,
        "explanation": "Session, Presentation, and Application are the User Support Layers."
    },

    // --- Topic: OSI Layers Functions ---
    {
        "question": "Which OSI layer deals with the transmission of raw bits over the physical medium?",
        "options": ["Data Link", "Physical", "Network", "Transport"],
        "correct": 1,
        "explanation": "The Physical layer handles raw bit transmission, physical topology, and bit synchronization."
    },
    {
        "question": "Bit synchronization is a function of which OSI layer?",
        "options": ["Data Link Layer", "Physical Layer", "Session Layer", "Network Layer"],
        "correct": 1,
        "explanation": "The Physical layer ensures that the sender and receiver are synchronized at the bit level."
    },
    {
        "question": "Which layer is responsible for Framing?",
        "options": ["Physical", "Data Link", "Network", "Transport"],
        "correct": 1,
        "explanation": "The Data Link layer divides the data from the network layer into manageable units called Frames."
    },
    {
        "question": "Physical Addressing (MAC address) is a function of which layer?",
        "options": ["Network Layer", "Data Link Layer", "Transport Layer", "Session Layer"],
        "correct": 1,
        "explanation": "The Data Link Layer uses physical addresses (MAC) to ensure frames reach the correct node."
    },
    {
        "question": "Logical Addressing (IP address) is handled by which layer?",
        "options": ["Data Link", "Network", "Transport", "Application"],
        "correct": 1,
        "explanation": "The Network layer provides logical addressing (IP) to route packets from source to destination."
    },
    {
        "question": "Routing (delivery of packets between networks) is performed by which layer?",
        "options": ["Data Link", "Network", "Session", "Transport"],
        "correct": 1,
        "explanation": "The Network layer handles routing to determine the best path for data to travel across networks."
    },
    {
        "question": "Which layer is responsible for Process-to-Process delivery?",
        "options": ["Network", "Data Link", "Transport", "Session"],
        "correct": 2,
        "explanation": "The Transport layer ensures delivery of messages from a specific process on the source to a specific process on the destination."
    },
    {
        "question": "Segmentation and Reassembly are functions of which layer?",
        "options": ["Application", "Presentation", "Transport", "Network"],
        "correct": 2,
        "explanation": "The Transport layer splits large messages into segments and reassembles them at the receiver."
    },
    {
        "question": "Which type of addressing does the Transport Layer use to identify a specific process?",
        "options": ["MAC Address", "IP Address", "Port Address", "URL"],
        "correct": 2,
        "explanation": "The Transport layer uses Port Addresses to identify specific processes or services on a host."
    },
    {
        "question": "Flow control at the Transport layer is performed:",
        "options": ["Node to Node", "End to End", "Hop to Hop", "Link to Link"],
        "correct": 1,
        "explanation": "Transport layer flow control is End-to-End, whereas Data Link flow control is Node-to-Node."
    },
    {
        "question": "Which layer manages Dialog Control and Synchronization?",
        "options": ["Transport", "Session", "Presentation", "Application"],
        "correct": 1,
        "explanation": "The Session layer establishes sessions, manages dialogs, and inserts synchronization points (checkpoints)."
    },
    {
        "question": "If a file transfer is interrupted, which layer's checkpoints allow it to resume rather than restart?",
        "options": ["Transport", "Session", "Network", "Application"],
        "correct": 1,
        "explanation": "The Session layer adds synchronization points (checkpoints) to recover from failures without restarting completely."
    },
    {
        "question": "Encryption, Decryption, and Compression are functions of which OSI layer?",
        "options": ["Application", "Presentation", "Session", "Transport"],
        "correct": 1,
        "explanation": "The Presentation layer handles translation, encryption, and compression of data."
    },
    {
        "question": "Which layer provides services directly to the user (e.g., Email, File Transfer)?",
        "options": ["Presentation", "Session", "Application", "Transport"],
        "correct": 2,
        "explanation": "The Application layer provides protocols (HTTP, FTP, SMTP) for user applications."
    },

    // --- Topic: TCP/IP Model ---
    {
        "question": "How many layers are in the TCP/IP model described in the text?",
        "options": ["7", "5", "4", "6"],
        "correct": 2,
        "explanation": "The TCP/IP model is described as a 4-layer hierarchical protocol suite."
    },
    {
        "question": "Which two OSI layers are absent (combined into Application) in the TCP/IP model?",
        "options": ["Network and Transport", "Session and Presentation", "Data Link and Physical", "Transport and Session"],
        "correct": 1,
        "explanation": "The Presentation and Session layers are not present as separate layers in the TCP/IP model."
    },
    {
        "question": "The 'Internet Layer' in the TCP/IP model corresponds to which layer in the OSI model?",
        "options": ["Physical Layer", "Data Link Layer", "Network Layer", "Transport Layer"],
        "correct": 2,
        "explanation": "The Internet Layer in TCP/IP is equivalent to the Network Layer in OSI."
    },
    {
        "question": "In the TCP/IP model, the Transport layer can offer which type of services?",
        "options": ["Only Connection-oriented", "Only Connectionless", "Choice between Connection and Connectionless", "Neither"],
        "correct": 2,
        "explanation": "Unlike OSI (strictly connection-oriented at Transport), TCP/IP Transport layer offers a choice (TCP or UDP)."
    },

    // --- Topic: Protocols & PDUs ---
    {
        "question": "What is the Protocol Data Unit (PDU) called at the Transport Layer?",
        "options": ["Frame", "Packet", "Segment", "Bit"],
        "correct": 2,
        "explanation": "The message unit at the Transport layer is called a Segment."
    },
    {
        "question": "What is the Protocol Data Unit (PDU) called at the Network Layer?",
        "options": ["Frame", "Datagram/Packet", "Segment", "Bit"],
        "correct": 1,
        "explanation": "At the Network/Internet layer, the data unit is called a Packet or Datagram."
    },
    {
        "question": "What is the Protocol Data Unit (PDU) called at the Data Link Layer?",
        "options": ["Frame", "Packet", "Segment", "Message"],
        "correct": 0,
        "explanation": "The Data Link layer processes data in units called Frames."
    },
    {
        "question": "Which of the following is an Application layer protocol?",
        "options": ["IP", "TCP", "SMTP", "Ethernet"],
        "correct": 2,
        "explanation": "SMTP (Simple Mail Transfer Protocol) is an Application layer protocol."
    },
    {
        "question": "UDP and TCP are protocols belonging to which layer?",
        "options": ["Internet", "Application", "Transport", "Link"],
        "correct": 2,
        "explanation": "UDP and TCP are Transport layer protocols."
    },
    {
        "question": "IP and ICMP are protocols belonging to which layer?",
        "options": ["Application", "Transport", "Internet", "Link"],
        "correct": 2,
        "explanation": "IP and ICMP belong to the Internet layer in the TCP/IP model."
    },
    {
        "question": "Which of the following protocols is used at the Link layer (TCP/IP)?",
        "options": ["DSL, SONET, Ethernet", "IP, ARP, RARP", "TCP, UDP", "HTTP, FTP"],
        "correct": 0,
        "explanation": "DSL, SONET, 802.11, and Ethernet are Link layer protocols."
    },
    {
        "question": "Which protocol is used for file transfer?",
        "options": ["HTTP", "SMTP", "FTP", "DNS"],
        "correct": 2,
        "explanation": "FTP (File Transfer Protocol) is used for file transfer."
    },
    {
        "question": "Which protocol is used for electronic mail?",
        "options": ["HTTP", "FTP", "SMTP", "DNS"],
        "correct": 2,
        "explanation": "SMTP (Simple Mail Transfer Protocol) is used for email."
    },

    // --- Topic: Advanced / Scenario Based ---
    {
        "question": "Which of the following is NOT a characteristic of 'Message Streams' compared to 'Byte Streams'?",
        "options": ["Packets have separate boundaries", "Used in connectionless services", "Packets are considered a single unit", "Preserves message boundaries"],
        "correct": 2,
        "explanation": "In Message streams, boundaries are preserved. In Byte streams, packets are considered a single unit (stream)."
    },
    {
        "question": "If a network has 3 routers and administrators can add 2 types of lines between each pair, how many topology combinations are possible?",
        "options": ["6", "9", "8", "3"],
        "correct": 2,
        "explanation": "3 routers = 3 links (PQ, QR, PR). Each link has 2 choices. Total = 2 * 2 * 2 = 8."
    },
    {
        "question": "Which layer is responsible for Access Control (deciding who accesses the link)?",
        "options": ["Physical", "Data Link", "Network", "Session"],
        "correct": 1,
        "explanation": "Access Control is a function of the Data Link layer (MAC sublayer)."
    },
    {
        "question": "In the context of headers, what is a 'Payload'?",
        "options": ["The header of the current layer", "The packet coming from the layer above (k+1)", "The packet coming from the layer below", "The tail of the packet"],
        "correct": 1,
        "explanation": "The payload field at layer k is the packet coming from the k+1 (upper) layer."
    },
    {
        "question": "What determines the boundaries of layers in the OSI model?",
        "options": ["Maximizing information flow", "Minimizing flow of information between layers", "Hardware constraints", "Software speed"],
        "correct": 1,
        "explanation": "Layer boundaries are decided to minimize the flow of information between layers."
    },
    {
        "question": "If the services at layer 'k' change, which layer is affected?",
        "options": ["Layer k-1", "Layer k+1", "Both layers", "No layers"],
        "correct": 1,
        "explanation": "Services are provided to the upper layer. If services at layer k change, layer k+1 (the user of the service) may be affected."
    },
    {
        "question": "If the algorithm (protocol) at layer 'k' changes, which layer is affected?",
        "options": ["Layer k-1", "Layer k+1", "No other layers", "All layers"],
        "correct": 2,
        "explanation": "Protocols are implementation details within a layer. Changing the algorithm does not affect other layers as long as the service remains the same."
    },
    {
        "question": "Data link layer performs error control node-to-node. How does the Transport layer perform error control?",
        "options": ["Node-to-node", "End-to-end", "Hop-to-hop", "It does not perform error control"],
        "correct": 1,
        "explanation": "The Transport layer performs error control End-to-End."
    },
    {
        "question": "Which layer deals with syntax and semantics of information?",
        "options": ["Application", "Presentation", "Session", "Transport"],
        "correct": 1,
        "explanation": "The Presentation layer is concerned with the syntax and semantics of the information exchanged."
    },
    {
        "question": "Which addressing is used to identify a host on a network?",
        "options": ["Port address", "Logical (IP) address", "Physical (MAC) address", "Specific address"],
        "correct": 1,
        "explanation": "Logical (IP) addresses are used to identify a host on a network."
    },
    {
        "question": "Which addressing is used to identify a specific process on a host?",
        "options": ["Port address", "Logical address", "Physical address", "MAC address"],
        "correct": 0,
        "explanation": "Port addresses identify a specific process on a host."
    },
    {
        "question": "In the TCP/IP model, the 'Host-to-Network' layer is another name for which layer?",
        "options": ["Internet Layer", "Link Layer", "Transport Layer", "Application Layer"],
        "correct": 1,
        "explanation": "The Link Layer in TCP/IP is sometimes referred to as the Host-to-Network layer."
    },
    {
        "question": "Which protocol allows 2 systems to communicate irrespective of their architecture?",
        "options": ["Proprietary protocols", "OSI Model", "Closed systems", "SNA"],
        "correct": 1,
        "explanation": "The OSI model allows two systems to communicate irrespective of their architecture (Open Systems)."
    },
    {
        "question": "In a Mesh topology with 10 devices, how many links are required?",
        "options": ["45", "90", "50", "10"],
        "correct": 0,
        "explanation": "N(N-1)/2 = 10*9/2 = 45."
    },
    {
        "question": "Which component of a data communication system is the 'channel' through which data is sent?",
        "options": ["Sender", "Receiver", "Medium", "Protocol"],
        "correct": 2,
        "explanation": "The Medium is the physical path or channel through which data flows."
    },
    {
        "question": "Frequency is measured in:",
        "options": ["Seconds", "Hertz", "Bits", "Bytes"],
        "correct": 1,
        "explanation": "Frequency is measured in Hertz (Hz)."
    },
    {
        "question": "Which layer is responsible for 'Access Control'?",
        "options": ["Physical", "Data Link", "Network", "Transport"],
        "correct": 1,
        "explanation": "The Data Link layer (specifically the MAC sublayer) handles access control."
    },
    {
        "question": "Which topology requires the most amount of cabling?",
        "options": ["Star", "Bus", "Ring", "Mesh"],
        "correct": 3,
        "explanation": "Mesh topology requires the most cabling due to n(n-1)/2 links."
    },
    {
        "question": "Which topology is easiest to install for small networks?",
        "options": ["Mesh", "Bus", "Ring", "Tree"],
        "correct": 1,
        "explanation": "Bus topology is easy to install and uses less cable for small networks."
    },
    {
        "question": "In Fiber optics, the source of light is usually:",
        "options": ["Sunlight", "LED or Laser", "Incandescent bulb", "Fluorescent lamp"],
        "correct": 1,
        "explanation": "Fiber optics use a light source, typically an LED or Laser."
    },
    {
        "question": "Unguided media transport electromagnetic waves without:",
        "options": ["Energy", "A physical conductor", "A receiver", "A sender"],
        "correct": 1,
        "explanation": "Unguided media (wireless) transport waves without a physical conductor."
    },
    {
        "question": "Which layer is responsible for 'Translation' of data?",
        "options": ["Application", "Presentation", "Session", "Transport"],
        "correct": 1,
        "explanation": "Translation (e.g., ASCII to EBCDIC) is a function of the Presentation layer."
    },
    {
        "question": "Which layer performs 'Route Discovery'?",
        "options": ["Data Link", "Network", "Transport", "Application"],
        "correct": 1,
        "explanation": "Route discovery (Routing) is the primary function of the Network layer."
    },
    {
        "question": "The 'Backbone' cable is a feature of which topology?",
        "options": ["Star", "Ring", "Bus", "Mesh"],
        "correct": 2,
        "explanation": "Bus topology uses a single long cable acting as a backbone."
    }
];